name: Deploy Flutter Web to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Install Flutter SDK di Server GitHub
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # Anda bisa menentukan versi spesifik jika perlu, misal: flutter-version: '3.19.0'
      
      # 2. Download library yang dibutuhkan
      - name: Install Dependencies
        run: flutter pub get

      # 3. Build Flutter Web (PENTING: Perhatikan bagian base-href)
      # GANTI "NAMA-REPO-ANDA" dengan nama repository github Anda.
      # Contoh: jika repo anda github.com/budi/toko-online, maka isi "/toko-online/"
      # Pastikan diawali dan diakhiri dengan garis miring (slash).
      - name: Build Web
        run: flutter build web --release --base-href "/custom_qr_maker/"

      # 4. Upload folder hasil build (build/web)
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/web'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4